### ISSUE TITLE
'Autorun' patch

### ISSUE THREAD

**Issue by R3D-C0M3T** [JackitK/Golden-Sun-Lost-Age-20th-Anniversary#1]
Hi, I just finished Golden Sun QOL & started TLA 20th, but I'm really missing the 'autorun' patch from QOL (run by default, hold b to walk). Is that something that could be adapted to work with/added to TLA 20th (as a separate patch for those that want it)?

Thanks for all the work that went into this btw, it's just what I was looking for =]

**Comment by JackitK** [comment]
Sure. 

While I didn't make the code for the auto-run patches, luckily there's one made of both game provided by the community.  I believe they're up on the Discord for the modding community. But I'll update the latest version to include a copy of the auto run patch to download.  Least I can do since I think it'll be awhile before QOL or Anniversary gets a new update proper.

**Comment by R3D-C0M3T** [comment]
Oh awesome! Searched around but couldn't find the existing one, thanks for adding it here, much appreciated!
